services:
  mongo:
    image: mongo:latest
    container_name: mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 5s

  app:
    build:
      context: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    environment:
      - MONGODB_URI=mongodb+srv://newlifedeu:W1hqkyLukCV8Mslw@cluster0.dqiy9.mongodb.net/Docker?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network
    restart: always
    command: node app.js

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  app_node_modules:
    driver: local